[phases.setup]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev", "libgomp1", "libgthread-2.0-0", "libopencv-dev"]

[start]
cmd = "gunicorn --chdir backend app.main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
