[phases.setup]
aptPkgs = [
  "libgl1",
  "libglib2.0-0",
  "libglx0",
  "libglvnd0",
  "libegl1",
  "libsm6",
  "libxext6",
  "libxrender1",
  "libgomp1",
  "ffmpeg"
]

[start]
cmd = "gunicorn --chdir backend app.main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
